// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VMS.Modules.Vehicles.Data;

#nullable disable

namespace VMS.Modules.Vehicles.Data.Migrations
{
    [DbContext(typeof(VehicleDbContext))]
    [Migration("20260922094230_VehicleReceipts")]
    partial class VehicleReceipts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("veh")
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VMS.Modules.Vehicles.Domain.DriverAssignment", b =>
                {
                    b.Property<int>("DriverAssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DriverAssignmentId"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("DriverId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date");

                    b.Property<string>("EndReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("DriverAssignmentId");

                    b.HasIndex("VehicleId");

                    b.HasIndex("TenantId", "DriverId")
                        .IsUnique()
                        .HasDatabaseName("UX_DriverAssignments_Driver")
                        .HasFilter("[EffectiveTo] IS NULL");

                    b.HasIndex("TenantId", "VehicleId")
                        .IsUnique()
                        .HasDatabaseName("UX_DriverAssignments_Vehicle")
                        .HasFilter("[EffectiveTo] IS NULL");

                    b.ToTable("DriverAssignments", "veh");
                });

            modelBuilder.Entity("VMS.Modules.Vehicles.Domain.OdometerReading", b =>
                {
                    b.Property<int>("OdometerReadingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OdometerReadingId"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("Km")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateOnly>("ReadingDate")
                        .HasColumnType("date");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("OdometerReadingId");

                    b.HasIndex("VehicleId");

                    b.HasIndex("TenantId", "VehicleId", "ReadingDate");

                    b.ToTable("OdometerReadings", "veh");
                });

            modelBuilder.Entity("VMS.Modules.Vehicles.Domain.Vehicle", b =>
                {
                    b.Property<int>("VehicleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehicleId"));

                    b.Property<DateOnly?>("AcquisitionDate")
                        .HasColumnType("date");

                    b.Property<string>("AcquisitionType")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("AxleConfigurationId")
                        .HasColumnType("int");

                    b.Property<int?>("BodyTypeId")
                        .HasColumnType("int");

                    b.Property<Guid?>("BranchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CapacityUnit")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("ChassisNo")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Colour")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("CurrentCategory")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("CurrentCounterpartyId")
                        .HasColumnType("int");

                    b.Property<int?>("DefaultDriverId")
                        .HasColumnType("int");

                    b.Property<string>("DraftData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EngineNo")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("FuelCardCompanyId")
                        .HasColumnType("int");

                    b.Property<string>("FuelCardNumber")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("FuelType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal?>("Gvw")
                        .HasColumnType("decimal(10,2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsInFleet")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bit")
                        .HasComputedColumnSql("CAST(CASE WHEN [Status] IN ('Active', 'Assigned', 'UnderMaintenance', 'TemporarilyUnavailable') AND [IsDeleted] = 0 THEN 1 ELSE 0 END AS bit)", true);

                    b.Property<bool>("IsLive")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bit")
                        .HasComputedColumnSql("CAST(CASE WHEN [Status] IN ('Sold', 'Transferred') OR [IsDeleted] = 1 THEN 0 ELSE 1 END AS bit)", true);

                    b.Property<decimal?>("LoadCapacity")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("MakeId")
                        .HasColumnType("int");

                    b.Property<int?>("ManufacturingYear")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("OpeningOdometer")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("OpeningOdometerDate")
                        .HasColumnType("date");

                    b.Property<string>("RegNoKey")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("RegistrationCityId")
                        .HasColumnType("int");

                    b.Property<string>("RegistrationNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Remarks")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.Property<decimal?>("TankCapacity")
                        .HasColumnType("decimal(10,2)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("TrackerCompanyId")
                        .HasColumnType("int");

                    b.Property<string>("TrackerDeviceId")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int?>("TyreCount")
                        .HasColumnType("int");

                    b.Property<string>("VehicleCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("VehicleTypeId")
                        .HasColumnType("int");

                    b.HasKey("VehicleId");

                    b.HasIndex("TenantId", "ChassisNo")
                        .IsUnique()
                        .HasDatabaseName("UX_Vehicles_Chassis")
                        .HasFilter("[ChassisNo] IS NOT NULL AND [Status] <> 'Sold' AND [Status] <> 'Transferred' AND [IsDeleted] = 0");

                    b.HasIndex("TenantId", "CurrentCategory");

                    b.HasIndex("TenantId", "DefaultDriverId");

                    b.HasIndex("TenantId", "EngineNo")
                        .IsUnique()
                        .HasDatabaseName("UX_Vehicles_Engine")
                        .HasFilter("[EngineNo] IS NOT NULL AND [Status] <> 'Sold' AND [Status] <> 'Transferred' AND [IsDeleted] = 0");

                    b.HasIndex("TenantId", "FuelCardNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_Vehicles_FuelCard")
                        .HasFilter("[FuelCardNumber] IS NOT NULL AND [Status] IN ('Active', 'Assigned', 'UnderMaintenance', 'TemporarilyUnavailable') AND [IsDeleted] = 0");

                    b.HasIndex("TenantId", "RegNoKey")
                        .IsUnique()
                        .HasDatabaseName("UX_Vehicles_RegNo")
                        .HasFilter("[Status] <> 'Sold' AND [Status] <> 'Transferred' AND [IsDeleted] = 0");

                    b.HasIndex("TenantId", "VehicleCode")
                        .IsUnique();

                    b.HasIndex("TenantId", "VehicleTypeId");

                    b.HasIndex("TenantId", "Status", "ModifiedOn");

                    b.ToTable("Vehicles", "veh");
                });

            modelBuilder.Entity("VMS.Modules.Vehicles.Domain.VehicleAcquisition", b =>
                {
                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.Property<decimal?>("AmountPaid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMode")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("PaymentReference")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<decimal?>("PurchasePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("RegistrationCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("SellerId")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("VehicleId");

                    b.HasIndex("TenantId");

                    b.ToTable("VehicleAcquisitions", "veh");
                });

            modelBuilder.Entity("VMS.Modules.Vehicles.Domain.VehicleAttachedItem", b =>
                {
                    b.Property<int>("VehicleAttachedItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehicleAttachedItemId"));

                    b.Property<string>("Condition")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<decimal?>("Cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("DetachReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateOnly?>("DetachedOn")
                        .HasColumnType("date");

                    b.Property<DateOnly>("InstallationDate")
                        .HasColumnType("date");

                    b.Property<int>("ItemTypeId")
                        .HasColumnType("int");

                    b.Property<string>("SerialNo")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<int?>("SupplierId")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("TransferredFromItemId")
                        .HasColumnType("int");

                    b.Property<int?>("TransferredToVehicleId")
                        .HasColumnType("int");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("WarrantyUntil")
                        .HasColumnType("date");

                    b.HasKey("VehicleAttachedItemId");

                    b.HasIndex("VehicleId");

                    b.HasIndex("TenantId", "SerialNo")
                        .IsUnique()
                        .HasDatabaseName("UX_VehicleItems_Serial")
                        .HasFilter("[SerialNo] IS NOT NULL AND [Status] = 'Attached'");

                    b.HasIndex("TenantId", "VehicleId", "Status");

                    b.ToTable("VehicleAttachedItems", "veh");
                });

            modelBuilder.Entity("VMS.Modules.Vehicles.Domain.VehicleFinanceAgreement", b =>
                {
                    b.Property<int>("VehicleFinanceAgreementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehicleFinanceAgreementId"));

                    b.Property<DateOnly>("AgreementDate")
                        .HasColumnType("date");

                    b.Property<string>("AgreementNo")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int>("BankId")
                        .HasColumnType("int");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DownPayment")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FinanceAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("FinanceTypeId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("FirstDueDate")
                        .HasColumnType("date");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<decimal>("InstallmentAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("MarkupRate")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("ResidualAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<decimal?>("SecurityDeposit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Tenure")
                        .HasColumnType("int");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("VehicleFinanceAgreementId");

                    b.HasIndex("VehicleId");

                    b.HasIndex("TenantId", "VehicleId")
                        .IsUnique()
                        .HasDatabaseName("UX_VehicleFinance_Open")
                        .HasFilter("[Status] IN ('Draft', 'Active')");

                    b.HasIndex("TenantId", "BankId", "AgreementNo")
                        .IsUnique()
                        .HasDatabaseName("UX_VehicleFinance_BankAgreement");

                    b.ToTable("VehicleFinanceAgreements", "veh");
                });

            modelBuilder.Entity("VMS.Modules.Vehicles.Domain.VehicleInstallment", b =>
                {
                    b.Property<int>("VehicleInstallmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehicleInstallmentId"));

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date");

                    b.Property<decimal>("ExpectedAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("InstallmentNo")
                        .HasColumnType("int");

                    b.Property<bool>("IsResidual")
                        .HasColumnType("bit");

                    b.Property<decimal>("PaidAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly?>("PaidOn")
                        .HasColumnType("date");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("VehicleFinanceAgreementId")
                        .HasColumnType("int");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("VehicleInstallmentId");

                    b.HasIndex("VehicleFinanceAgreementId", "InstallmentNo")
                        .IsUnique();

                    b.HasIndex("TenantId", "VehicleId", "DueDate");

                    b.ToTable("VehicleInstallments", "veh");
                });

            modelBuilder.Entity("VMS.Modules.Vehicles.Domain.VehicleLifecycleEntry", b =>
                {
                    b.Property<int>("VehicleLifecycleEntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehicleLifecycleEntryId"));

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("CounterpartyId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("EffectiveDate")
                        .HasColumnType("date");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("FromCategory")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("FromStatus")
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.Property<DateTime>("OccurredOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Reference")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ToCategory")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ToStatus")
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("VehicleLifecycleEntryId");

                    b.HasIndex("VehicleId");

                    b.HasIndex("TenantId", "VehicleId", "OccurredOn");

                    b.ToTable("VehicleLifecycle", "veh");
                });

            modelBuilder.Entity("VMS.Modules.Vehicles.Domain.VehicleRelation", b =>
                {
                    b.Property<int>("VehicleRelationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehicleRelationId"));

                    b.Property<decimal?>("AgreedAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly?>("AgreementEndDate")
                        .HasColumnType("date");

                    b.Property<string>("AgreementReference")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("ArrangementType")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("CounterpartyId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date");

                    b.Property<string>("ExpenseSharingRule")
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.Property<decimal?>("FixedMonthlyAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("RentAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("RentDueDay")
                        .HasColumnType("int");

                    b.Property<string>("RentFrequency")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal?>("RevenueSharePercent")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("SecurityDeposit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("SharePercent")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("SharingBasis")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("VehicleRelationId");

                    b.HasIndex("VehicleId");

                    b.HasIndex("TenantId", "CounterpartyId");

                    b.HasIndex("TenantId", "VehicleId")
                        .IsUnique()
                        .HasDatabaseName("UX_VehicleRelations_Open")
                        .HasFilter("[EffectiveTo] IS NULL");

                    b.ToTable("VehicleRelations", "veh");
                });

            modelBuilder.Entity("VMS.Modules.Vehicles.Domain.VehicleTransaction", b =>
                {
                    b.Property<int>("VehicleTransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehicleTransactionId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("InstallmentId")
                        .HasColumnType("int");

                    b.Property<bool>("IsSystemGenerated")
                        .HasColumnType("bit");

                    b.Property<int?>("PartnerId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ReceiptContentType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ReceiptFileName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ReceiptSha256")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<long?>("ReceiptSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("ReceiptStorageKey")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Reference")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int?>("ReversesTransactionId")
                        .HasColumnType("int");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SubType")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("TransactionDate")
                        .HasColumnType("date");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("VehicleTransactionId");

                    b.HasIndex("InstallmentId");

                    b.HasIndex("ReversesTransactionId")
                        .IsUnique()
                        .HasDatabaseName("UX_VehicleTransactions_Reversal")
                        .HasFilter("[ReversesTransactionId] IS NOT NULL");

                    b.HasIndex("VehicleId");

                    b.HasIndex("TenantId", "VehicleId", "TransactionDate");

                    b.HasIndex("TenantId", "VehicleId", "Type");

                    b.ToTable("VehicleTransactions", "veh");
                });

            modelBuilder.Entity("VMS.Shared.Auditing.AuditEntry", b =>
                {
                    b.Property<long>("AuditEntryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AuditEntryID"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Entity")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Field")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("NewValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("OldValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("RecordId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RequiredPermission")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RootEntity")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RootRecordId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("AuditEntryID");

                    b.HasIndex("GroupId");

                    b.HasIndex("TenantId", "OccurredAt");

                    b.HasIndex("TenantId", "UserId", "OccurredAt");

                    b.HasIndex("TenantId", "Entity", "RecordId", "OccurredAt");

                    b.HasIndex("TenantId", "RootEntity", "RootRecordId", "OccurredAt");

                    b.ToTable("AuditEntries", "core", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("VMS.Modules.Vehicles.Domain.DriverAssignment", b =>
                {
                    b.HasOne("VMS.Modules.Vehicles.Domain.Vehicle", null)
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("VMS.Modules.Vehicles.Domain.OdometerReading", b =>
                {
                    b.HasOne("VMS.Modules.Vehicles.Domain.Vehicle", null)
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("VMS.Modules.Vehicles.Domain.VehicleAcquisition", b =>
                {
                    b.HasOne("VMS.Modules.Vehicles.Domain.Vehicle", null)
                        .WithOne()
                        .HasForeignKey("VMS.Modules.Vehicles.Domain.VehicleAcquisition", "VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("VMS.Modules.Vehicles.Domain.VehicleAttachedItem", b =>
                {
                    b.HasOne("VMS.Modules.Vehicles.Domain.Vehicle", null)
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("VMS.Modules.Vehicles.Domain.VehicleFinanceAgreement", b =>
                {
                    b.HasOne("VMS.Modules.Vehicles.Domain.Vehicle", null)
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("VMS.Modules.Vehicles.Domain.VehicleInstallment", b =>
                {
                    b.HasOne("VMS.Modules.Vehicles.Domain.VehicleFinanceAgreement", null)
                        .WithMany()
                        .HasForeignKey("VehicleFinanceAgreementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("VMS.Modules.Vehicles.Domain.VehicleLifecycleEntry", b =>
                {
                    b.HasOne("VMS.Modules.Vehicles.Domain.Vehicle", null)
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("VMS.Modules.Vehicles.Domain.VehicleRelation", b =>
                {
                    b.HasOne("VMS.Modules.Vehicles.Domain.Vehicle", null)
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("VMS.Modules.Vehicles.Domain.VehicleTransaction", b =>
                {
                    b.HasOne("VMS.Modules.Vehicles.Domain.VehicleInstallment", null)
                        .WithMany()
                        .HasForeignKey("InstallmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VMS.Modules.Vehicles.Domain.VehicleTransaction", null)
                        .WithMany()
                        .HasForeignKey("ReversesTransactionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VMS.Modules.Vehicles.Domain.Vehicle", null)
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
