// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VMS.Modules.BusinessPartners.Data;

#nullable disable

namespace VMS.Modules.BusinessPartners.Data.Migrations
{
    [DbContext(typeof(PartnerDbContext))]
    [Migration("20260920090512_InitialPartners")]
    partial class InitialPartners
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("bp")
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VMS.Modules.BusinessPartners.Domain.BpAddress", b =>
                {
                    b.Property<int>("BpAddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BpAddressId"));

                    b.Property<string>("AddressType")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("BusinessPartnerId")
                        .HasColumnType("int");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<string>("Landmark")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Line1")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Line2")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("ProvinceCode")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("BpAddressId");

                    b.HasIndex("BusinessPartnerId")
                        .IsUnique()
                        .HasDatabaseName("UX_BpAddresses_Primary")
                        .HasFilter("[IsPrimary] = 1");

                    b.HasIndex("TenantId");

                    b.ToTable("BpAddresses", "bp");
                });

            modelBuilder.Entity("VMS.Modules.BusinessPartners.Domain.BpBankAccount", b =>
                {
                    b.Property<int>("BpBankAccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BpBankAccountId"));

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("nvarchar(34)");

                    b.Property<string>("AccountTitle")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("BranchCode")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("BusinessPartnerId")
                        .HasColumnType("int");

                    b.Property<string>("Iban")
                        .HasMaxLength(34)
                        .HasColumnType("nvarchar(34)");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("BpBankAccountId");

                    b.HasIndex("BusinessPartnerId")
                        .IsUnique()
                        .HasDatabaseName("UX_BpBankAccounts_Primary")
                        .HasFilter("[IsPrimary] = 1");

                    b.HasIndex("TenantId");

                    b.HasIndex("BusinessPartnerId", "BankName", "AccountNumber")
                        .IsUnique();

                    b.ToTable("BpBankAccounts", "bp");
                });

            modelBuilder.Entity("VMS.Modules.BusinessPartners.Domain.BpContact", b =>
                {
                    b.Property<int>("BpContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BpContactId"));

                    b.Property<int>("BusinessPartnerId")
                        .HasColumnType("int");

                    b.Property<string>("ContactName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Designation")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Notes")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("BpContactId");

                    b.HasIndex("BusinessPartnerId")
                        .IsUnique()
                        .HasDatabaseName("UX_BpContacts_Primary")
                        .HasFilter("[IsPrimary] = 1");

                    b.HasIndex("TenantId");

                    b.ToTable("BpContacts", "bp");
                });

            modelBuilder.Entity("VMS.Modules.BusinessPartners.Domain.BpCustomerDetail", b =>
                {
                    b.Property<int>("BusinessPartnerId")
                        .HasColumnType("int");

                    b.Property<string>("BillingCycle")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int?>("CreditDays")
                        .HasColumnType("int");

                    b.Property<decimal?>("CreditLimit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CustomerType")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<decimal?>("DefaultRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RateBasis")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("BusinessPartnerId");

                    b.HasIndex("TenantId");

                    b.ToTable("BpCustomerDetails", "bp");
                });

            modelBuilder.Entity("VMS.Modules.BusinessPartners.Domain.BpDriverDetail", b =>
                {
                    b.Property<int>("BusinessPartnerId")
                        .HasColumnType("int");

                    b.Property<string>("BloodGroup")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("CommissionBasis")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal?>("CommissionValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly?>("DateOfJoining")
                        .HasColumnType("date");

                    b.Property<bool>("DriverAppAccess")
                        .HasColumnType("bit");

                    b.Property<string>("EmergencyContactName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EmergencyContactPhone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("EmploymentType")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("Guarantor")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateOnly>("LicenceExpiryDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("LicenceIssueDate")
                        .HasColumnType("date");

                    b.Property<string>("LicenceNo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("LicenceType")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<decimal?>("MonthlyRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("BusinessPartnerId");

                    b.HasIndex("TenantId", "LicenceNo");

                    b.ToTable("BpDriverDetails", "bp");
                });

            modelBuilder.Entity("VMS.Modules.BusinessPartners.Domain.BpRoleLog", b =>
                {
                    b.Property<int>("BpRoleLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BpRoleLogId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("BusinessPartnerId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("EffectiveDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("OccurredOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("RoleCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("BpRoleLogId");

                    b.HasIndex("TenantId");

                    b.HasIndex("BusinessPartnerId", "OccurredOn");

                    b.ToTable("BpRoleLog", "bp");
                });

            modelBuilder.Entity("VMS.Modules.BusinessPartners.Domain.BpStatusLog", b =>
                {
                    b.Property<int>("BpStatusLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BpStatusLogId"));

                    b.Property<int>("BusinessPartnerId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("EffectiveDate")
                        .HasColumnType("date");

                    b.Property<string>("FromStatus")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<DateTime>("OccurredOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("BpStatusLogId");

                    b.HasIndex("TenantId");

                    b.HasIndex("BusinessPartnerId", "OccurredOn");

                    b.ToTable("BpStatusLog", "bp");
                });

            modelBuilder.Entity("VMS.Modules.BusinessPartners.Domain.BpVendorDetail", b =>
                {
                    b.Property<int>("BusinessPartnerId")
                        .HasColumnType("int");

                    b.Property<decimal?>("CreditLimit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PaymentTermDays")
                        .HasColumnType("int");

                    b.Property<string>("SupplyCategories")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("BusinessPartnerId");

                    b.HasIndex("TenantId");

                    b.ToTable("BpVendorDetails", "bp");
                });

            modelBuilder.Entity("VMS.Modules.BusinessPartners.Domain.BusinessPartner", b =>
                {
                    b.Property<int>("BusinessPartnerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BusinessPartnerId"));

                    b.Property<string>("AddressLine")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("AlternatePhone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("BpCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid?>("BranchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("Cnic")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FilerStatus")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LegalName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Ntn")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<decimal>("OpeningBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly?>("OpeningBalanceDate")
                        .HasColumnType("date");

                    b.Property<string>("PartyType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("PrimaryMobile")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("StatusReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Strn")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("BusinessPartnerId");

                    b.HasIndex("TenantId", "BpCode")
                        .IsUnique();

                    b.HasIndex("TenantId", "CityId");

                    b.HasIndex("TenantId", "Cnic")
                        .IsUnique()
                        .HasDatabaseName("UX_BusinessPartners_Cnic")
                        .HasFilter("[Cnic] IS NOT NULL AND [Status] <> 'Merged' AND [IsDeleted] = 0");

                    b.HasIndex("TenantId", "LegalName");

                    b.HasIndex("TenantId", "Ntn")
                        .IsUnique()
                        .HasDatabaseName("UX_BusinessPartners_Ntn")
                        .HasFilter("[Ntn] IS NOT NULL AND [PartyType] = 'Company' AND [Status] <> 'Merged' AND [IsDeleted] = 0");

                    b.HasIndex("TenantId", "PrimaryMobile");

                    b.HasIndex("TenantId", "Strn")
                        .IsUnique()
                        .HasDatabaseName("UX_BusinessPartners_Strn")
                        .HasFilter("[Strn] IS NOT NULL AND [IsDeleted] = 0");

                    b.HasIndex("TenantId", "Status", "ModifiedOn");

                    b.ToTable("BusinessPartners", "bp");
                });

            modelBuilder.Entity("VMS.Modules.BusinessPartners.Domain.BusinessPartnerRole", b =>
                {
                    b.Property<int>("BpRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BpRoleId"));

                    b.Property<int>("BusinessPartnerId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("RoleCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("BpRoleId");

                    b.HasIndex("BusinessPartnerId", "RoleCode")
                        .IsUnique();

                    b.HasIndex("TenantId", "RoleCode", "IsActive");

                    b.ToTable("BusinessPartnerRoles", "bp");
                });

            modelBuilder.Entity("VMS.Shared.Auditing.AuditEntry", b =>
                {
                    b.Property<long>("AuditEntryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AuditEntryID"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Entity")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Field")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("NewValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("OldValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("RecordId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RequiredPermission")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("AuditEntryID");

                    b.HasIndex("GroupId");

                    b.HasIndex("TenantId", "OccurredAt");

                    b.HasIndex("TenantId", "UserId", "OccurredAt");

                    b.HasIndex("TenantId", "Entity", "RecordId", "OccurredAt");

                    b.ToTable("AuditEntries", "core", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("VMS.Modules.BusinessPartners.Domain.BpAddress", b =>
                {
                    b.HasOne("VMS.Modules.BusinessPartners.Domain.BusinessPartner", null)
                        .WithMany("Addresses")
                        .HasForeignKey("BusinessPartnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VMS.Modules.BusinessPartners.Domain.BpBankAccount", b =>
                {
                    b.HasOne("VMS.Modules.BusinessPartners.Domain.BusinessPartner", null)
                        .WithMany("BankAccounts")
                        .HasForeignKey("BusinessPartnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VMS.Modules.BusinessPartners.Domain.BpContact", b =>
                {
                    b.HasOne("VMS.Modules.BusinessPartners.Domain.BusinessPartner", null)
                        .WithMany("Contacts")
                        .HasForeignKey("BusinessPartnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VMS.Modules.BusinessPartners.Domain.BpCustomerDetail", b =>
                {
                    b.HasOne("VMS.Modules.BusinessPartners.Domain.BusinessPartner", null)
                        .WithOne("Customer")
                        .HasForeignKey("VMS.Modules.BusinessPartners.Domain.BpCustomerDetail", "BusinessPartnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VMS.Modules.BusinessPartners.Domain.BpDriverDetail", b =>
                {
                    b.HasOne("VMS.Modules.BusinessPartners.Domain.BusinessPartner", null)
                        .WithOne("Driver")
                        .HasForeignKey("VMS.Modules.BusinessPartners.Domain.BpDriverDetail", "BusinessPartnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VMS.Modules.BusinessPartners.Domain.BpVendorDetail", b =>
                {
                    b.HasOne("VMS.Modules.BusinessPartners.Domain.BusinessPartner", null)
                        .WithOne("Vendor")
                        .HasForeignKey("VMS.Modules.BusinessPartners.Domain.BpVendorDetail", "BusinessPartnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VMS.Modules.BusinessPartners.Domain.BusinessPartnerRole", b =>
                {
                    b.HasOne("VMS.Modules.BusinessPartners.Domain.BusinessPartner", null)
                        .WithMany("Roles")
                        .HasForeignKey("BusinessPartnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VMS.Modules.BusinessPartners.Domain.BusinessPartner", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("BankAccounts");

                    b.Navigation("Contacts");

                    b.Navigation("Customer");

                    b.Navigation("Driver");

                    b.Navigation("Roles");

                    b.Navigation("Vendor");
                });
#pragma warning restore 612, 618
        }
    }
}
